# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 20:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(default=datetime.datetime(2016, 3, 9, 20, 42, 29, 488272, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='core.Artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='core.Album'),
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together=set([('track', 'album')]),
        ),
    ]
